version: '3.8'

services:
  dockerregistry:
    image: registry.sriviz.com/dockerregistry:latest
    container_name: dockerregistry-ui
    restart: unless-stopped
    ports:
      - "5174:80"
    networks:
      - registry-net

networks:
  registry-net:
    external: true
    name: registry-net
