version: '3.8'

services:
  dockerregistry:
    image: localhost:5000/dockerregistry:latest
    container_name: dockerregistry-ui
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - registry-net

networks:
  registry-net:
    external: true
    name: registry-net
